# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_searchterm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchTerm',
        ),
    ]
